"""Enhanced document processing features

Revision ID: 002_enhanced_docs
Revises: 001_initial
Create Date: 2025-08-21 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002_enhanced_docs'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to documents table
    op.add_column('documents', sa.Column('batch_id', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('text_confidence', sa.Float(), nullable=True, default=0.0))
    op.add_column('documents', sa.Column('handwriting_detected', sa.Boolean(), nullable=True, default=False))
    op.add_column('documents', sa.Column('processing_method', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('processing_time', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True, default=1))
    op.add_column('documents', sa.Column('detected_rooms', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('detected_measurements', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('detected_tables', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('image_quality_score', sa.Float(), nullable=True, default=0.0))
    op.add_column('documents', sa.Column('text_density', sa.Float(), nullable=True, default=0.0))
    
    # Rename column to match new schema
    op.alter_column('documents', 'mime_type', 
                    existing_type=sa.String(length=100),
                    new_column_name='mime_type',
                    nullable=True)
    
    # Add indexes for better performance
    op.create_index(op.f('ix_documents_batch_id'), 'documents', ['batch_id'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_batch_id'), table_name='documents')
    
    # Remove added columns
    op.drop_column('documents', 'text_density')
    op.drop_column('documents', 'image_quality_score')
    op.drop_column('documents', 'detected_tables')
    op.drop_column('documents', 'detected_measurements')
    op.drop_column('documents', 'detected_rooms')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'processing_time')
    op.drop_column('documents', 'processing_method')
    op.drop_column('documents', 'handwriting_detected')
    op.drop_column('documents', 'text_confidence')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'batch_id')
    
    # ### end Alembic commands ###